doctrine:
    dbal:
        # configure these for your database server
        # use postgresql for PostgreSQL
        # use sqlite for SQLite
        driver: 'mysql'
        server_version: '5.7'

        # only needed for MySQL
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
          date: CsrDelft\common\Doctrine\Type\DateImmutableType
          datetime: CsrDelft\common\Doctrine\Type\DateTimeImmutableType
          datetimetz: CsrDelft\common\Doctrine\Type\DateTimeTzImmutableType
          changelog: CsrDelft\common\Doctrine\Type\ChangeLogType
          longtext: CsrDelft\common\Doctrine\Type\LongTextType
          uid: CsrDelft\common\Doctrine\Type\UidType
          stringkey: CsrDelft\common\Doctrine\Type\StringKeyType
          enumontvangtcontactueel: CsrDelft\common\Doctrine\Type\OntvangtContactueelType
          enumboekexemplaarstatus: CsrDelft\common\Doctrine\Type\BoekExemplaarStatusType
          enumcourantcategorie: CsrDelft\common\Doctrine\Type\CourantCategorieType
          enumforumdraadmeldingniveau: CsrDelft\common\Doctrine\Type\ForumDraadMeldingNiveauType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
          # Zie https://github.com/beberlei/DoctrineExtensions voor meer mooie extensies.
          string_functions:
            date: DoctrineExtensions\Query\Mysql\Date
            match: DoctrineExtensions\Query\Mysql\MatchAgainst
            unix_timestamp: DoctrineExtensions\Query\Mysql\UnixTimestamp
            day: DoctrineExtensions\Query\Mysql\Day
            month: DoctrineExtensions\Query\Mysql\Month
            dayofyear: DoctrineExtensions\Query\Mysql\DayOfYear
            now: DoctrineExtensions\Query\Mysql\Now
        mappings:
            CsrDelft:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/lib/entity'
                prefix: 'CsrDelft\entity'
                alias: App

