nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Bar-Token']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
        '^/api/v3/':
          origin_regex: true
          allow_origin: [ '^http://localhost:[0-9]+', '^https://bar.csrdelft.nl$' ]
          allow_headers: [ 'x-bar-token' ]
          allow_methods: [ 'OPTIONS', 'POST', 'PUT', 'GET', 'DELETE' ]
          max_age: 3600
#          hosts: [ '^api\.' ]
