nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: [ ]
    allow_headers: [ ]
    allow_methods: [ ]
    expose_headers: [ ]
    max_age: 0
    hosts: [ ]
    origin_regex: false
    forced_allow_origin_value: ~
  paths:
    '^/api/v3':
      origin_regex: true
      allow_origin: [ '%env(CORS_ALLOW_ORIGIN_API)%' ]
      allow_headers: [ 'authorization', 'content-type', 'x-bar-token' ]
      allow_methods: [ 'OPTIONS', 'POST', 'PUT', 'GET', 'DELETE' ]
      max_age: 3600
