language: php
php:
  - 7

cache:
  directories:
    - "node_modules"
    - "vendor"

services:
  - mysql

before_install:
  - cp ./bin/ci/mysql.ini.travis ./etc/mysql.ini
  - cp ./lib/defines.include.php.development.sample ./lib/defines.include.php
  - mysql -e 'CREATE DATABASE IF NOT EXISTS csrdelft;'
  - nvm install 8

install:
  - yarn
  - composer install

script:
  - yarn run production
  - composer run-script production

deploy:
  provider: script
  script: ./bin/ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master
