version: '3'

volumes:
  mysqldata:
    driver: local

services:
  stek:
    build:
      context: .
      dockerfile: "conf/Dockerfile-stek"
    ports:
      - "8080:80" # Expose stek op poort 8080
    volumes:
      - ./:/app
      - ./conf/dev/defines.include.php:/app/lib/defines.include.php
      - ./conf/dev/mysql.ini:/app/etc/mysql.ini
      - ./vendor:/app/vendor

  composer:
    build:
      context: .
      dockerfile: "conf/Dockerfile-composer"
    command: install --ignore-platform-reqs # Doe initieel een install
    volumes:
      - ./:/app
      - ./conf/dev/defines.include.php:/app/lib/defines.include.php
      - ./conf/dev/mysql.ini:/app/etc/mysql.ini
      - ./vendor:/app/vendor

  stekdb:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: bl44t
      MYSQL_USER: csrdelft
      MYSQL_PASSWORD: bl44t
      MYSQL_DATABASE: csrdelft
    volumes:
      - mysqldata:/var/lib/mysql/
      - ./data:/docker-entrypoint-initdb.d # laad sql bestanden
    ports:
      - "3306:3306" # Expose mysql op poort 3306

  yarn:
    build:
      context: .
      dockerfile: "conf/Dockerfile-yarn"
    volumes:
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.eslintrc.js:/app/.eslintrc.js
      - ./webpack.config.js:/app/webpack.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./htdocs/dist:/app/htdocs/dist
      - ./resources/assets:/app/resources/assets
      - ./node_modules:/app/node_modules
