version: '3'

volumes:
  mysqldata:
    driver: local

services:
  stek:
    build:
      context: .
      dockerfile: "conf/Dockerfile-stek"
    ports:
      - "8080:80" # Expose stek op poort 8080
    volumes:
      - ./:/var/www/csrdelft.nl
      - ./conf/dev/defines.include.php:/var/www/csrdelft.nl/lib/defines.include.php
      - ./conf/dev/mysql.ini:/var/www/csrdelft.nl/etc/mysql.ini
      - ./vendor:/var/www/csrdelft.nl/vendor

  composer:
    build:
      context: .
      dockerfile: "conf/Dockerfile-composer"
    command: install # Doe initieel een install
    volumes:
      - ./vendor:/app/vendor
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock

  stekdb:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: bl44t
      MYSQL_USER: csrdelft
      MYSQL_PASSWORD: bl44t
      MYSQL_DATABASE: csrdelft
    volumes:
      - mysqldata:/var/lib/mysql/
      - ./data:/docker-entrypoint-initdb.d # laad sql bestanden
    ports:
      - "3306:3306" # Expose mysql op poort 3306

  yarn:
    build:
      context: .
      dockerfile: "conf/Dockerfile-yarn"
    volumes:
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./webpack.mix.js:/app/webpack.mix.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./htdocs/dist:/app/htdocs/dist
      - ./resources/assets:/app/resources/assets
      - ./node_modules:/app/node_modules
