agenda-zoeken:
  path: /agenda/zoeken
  controller: CsrDelft\controller\AgendaController::zoeken
  methods: GET
  defaults: { _mag: P_AGENDA_READ }

agenda-details:
  path: /agenda/details/{uuid}
  controller: CsrDelft\controller\AgendaController::details
  methods: GET
  defaults: { _mag: P_LOGGED_IN }

agenda-feed:
  path: /agenda/feed
  controller: CsrDelft\controller\AgendaController::feed
  methods: GET
  defaults: { _mag: P_LOGGED_IN }

agenda-verplaatsen:
  path: /agenda/verplaatsen/{uuid}
  controller: CsrDelft\controller\AgendaController::verplaatsen
  methods: POST
  defaults: { _mag: P_LOGGED_IN } # controller checkt rechten

agenda-ics-item:
  path: /agenda/export/{uuid}.ics
  controller: CsrDelft\controller\AgendaController::export
  methods: GET
  requirements: { uuid: '.+' }
  defaults: { _mag: P_LOGGED_IN }

agenda-thuis:
  path: /agenda/{jaar}/{maand}
  controller: CsrDelft\controller\AgendaController::maand
  methods: GET
  defaults: { jaar: null, maand: null, _mag: P_AGENDA_READ }

agenda-maand:
  path: /agenda/maand/{jaar}/{maand}
  controller: CsrDelft\controller\AgendaController::maand
  methods: GET
  defaults: { jaar: null, maand: null, _mag: P_AGENDA_READ }

agenda-ics:
  path: /agenda/ical/{token}/csrdelft.ics
  controller: CsrDelft\controller\AgendaController::ical
  methods: GET
  defaults: { _mag: P_PUBLIC }

agenda-courant:
  path: /agenda/courant
  controller: CsrDelft\controller\AgendaController::courant
  methods: POST
  defaults: { _mag: P_MAIL_COMPOSE }

agenda-toevoegen:
  path: /agenda/toevoegen/{datum}
  controller: CsrDelft\controller\AgendaController::toevoegen
  methods: POST
  defaults: { datum: null, _mag: P_LOGGED_IN } # controller checkt rechten

agenda-bewerken:
  path: /agenda/bewerken/{aid}
  controller: CsrDelft\controller\AgendaController::bewerken
  methods: POST
  requirements: { aid: '\d+'}
  defaults: { _mag: P_LOGGED_IN } # controller checkt rechten

agenda-verwijderen:
  path: /agenda/verwijderen/{aid}
  controller: CsrDelft\controller\AgendaController::verwijderen
  methods: POST
  requirements: { aid: '\d+'}
  defaults: { _mag: P_AGENDA_MOD }

agenda-verbergen:
  path: /agenda/verbergen/{refuuid}
  controller: CsrDelft\controller\AgendaController::verbergen
  methods: POST
  defaults: { refuuid: null, _mag: P_LOGGED_IN }

