bibliotheek-overzicht:
  path: /bibliotheek
  controller: CsrDelft\controller\BibliotheekController::catalogustonen
  methods: GET
  defaults: { _mag: P_BIEB_READ }

bibliotheek-overzicht-data:
  path: /bibliotheek/catalogusdata
  controller: CsrDelft\controller\BibliotheekController::catalogusdata
  methods: POST
  defaults: { _mag: P_BIEB_READ }

bibliotheek-rubrieken:
  path: /bibliotheek/rubrieken
  controller: CsrDelft\controller\BibliotheekController::rubrieken
  methods: GET
  defaults: { _mag: P_BIEB_READ }

bibliotheek-wenslijst:
  path: /bibliotheek/wenslijst
  controller: CsrDelft\controller\BibliotheekController::wenslijst
  methods: GET
  defaults: { _mag: P_BIEB_READ }

bibliotheek-zoeken:
  path: /bibliotheek/zoeken
  controller: CsrDelft\controller\BibliotheekController::zoeken
  methods: POST
  defaults: { _mag: P_BIEB_READ }

bibliotheek-autocomplete:
  path: /bibliotheek/autocomplete/{zoekveld}
  controller: CsrDelft\controller\BibliotheekController::autocomplete
  methods: GET
  defaults: { _mag: P_BIEB_READ }

bibliotheek-boek:
  path: /bibliotheek/boek/{boek_id}
  controller: CsrDelft\controller\BibliotheekController::boek
  methods: [GET,POST]
  defaults: { boek_id: null, _mag: P_BIEB_READ }
  requirements: { boek_id: '\d+' }

bibliotheek-recensie:
  path: /bibliotheek/boek/{boek_id}/recensie
  controller: CsrDelft\controller\BibliotheekController::recensie
  methods: POST
  requirements: { boek_id: '\d+' }
  defaults: { _mag: P_BIEB_READ }

bibliotheek-verwijderboek:
  path: /bibliotheek/verwijderboek/{boek_id}
  controller: CsrDelft\controller\BibliotheekController::verwijderboek
  methods: POST
  requirements: { boek_id: '\d+' }
  defaults: { _mag: P_BIEB_READ }

bibliotheek-verwijderbeschrijving:
  path: /bibliotheek/verwijderbeschrijving/{boek_id}/{uid}
  controller: CsrDelft\controller\BibliotheekController::verwijderbeschrijving
  methods: POST
  requirements: { boek_id: '\d+', uid: '.{4}' }
  defaults: { _mag: P_BIEB_READ }

bibliotheek-exemplaar:
  path: /bibliotheek/exemplaar/{exemplaar_id}
  controller: CsrDelft\controller\BibliotheekController::exemplaar
  methods: POST
  requirements: { exemplaar_id: '\d+' }
  defaults: { _mag: P_BIEB_READ }

bibliotheek-addexemplaar:
  path: /bibliotheek/addexemplaar/{boek_id}/{uid}
  controller: CsrDelft\controller\BibliotheekController::addexemplaar
  methods: POST
  defaults: { uid: null, _mag: P_BIEB_READ }
  requirements: { boek_id: '\d+', uid: '.{4}' }

bibliotheek-verwijderexemplaar:
  path: /bibliotheek/verwijderexemplaar/{exemplaar_id}
  controller: CsrDelft\controller\BibliotheekController::verwijderexemplaar
  methods: POST
  requirements: { exemplaar_id: '\d+' }
  defaults: { _mag: P_BIEB_READ }

bibliotheek-exemplaarlenen:
  path: /bibliotheek/exemplaarlenen/{exemplaar_id}
  controller: CsrDelft\controller\BibliotheekController::exemplaarlenen
  methods: POST
  requirements: { exemplaar_id: '\d+' }
  defaults: { _mag: P_BIEB_READ }

bibliotheek-exemplaarteruggegeven:
  path: /bibliotheek/exemplaarteruggegeven/{exemplaar_id}
  controller: CsrDelft\controller\BibliotheekController::exemplaarteruggegeven
  methods: POST
  requirements: { exemplaar_id: '\d+' }
  defaults: { _mag: P_BIEB_READ }

bibliotheek-exemplaarterugontvangen:
  path: /bibliotheek/exemplaarterugontvangen/{exemplaar_id}
  controller: CsrDelft\controller\BibliotheekController::exemplaarterugontvangen
  methods: POST
  requirements: { exemplaar_id: '\d+' }
  defaults: { _mag: P_BIEB_READ }

bibliotheek-exemplaarvermist:
  path: /bibliotheek/exemplaarvermist/{exemplaar_id}
  controller: CsrDelft\controller\BibliotheekController::exemplaarvermist
  methods: POST
  requirements: { exemplaar_id: '\d+' }
  defaults: { _mag: P_BIEB_READ }

bibliotheek-exemplaargevonden:
  path: /bibliotheek/exemplaargevonden/{exemplaar_id}
  controller: CsrDelft\controller\BibliotheekController::exemplaargevonden
  methods: POST
  requirements: { exemplaar_id: '\d+' }
  defaults: { _mag: P_BIEB_READ }

bibliotheek-import:
  path: /bibliotheek/import/{boek_id}
  controller: CsrDelft\controller\BibliotheekController::import
  methods: POST
  requirements: { boek_id: '\d+' }
  defaults: { _mag: P_BIEB_READ }
