corvee-voorkeuren-beheer:
  path: /corvee/voorkeuren/beheer
  controller: CsrDelft\controller\maalcie\BeheerVoorkeurenController::beheer
  methods: GET
  options: { mag: P_CORVEE_MOD }

corvee-voorkeuren-beheer-inschakelen:
  path: /corvee/voorkeuren/beheer/inschakelen/{crid}/{uid}
  controller: CsrDelft\controller\maalcie\BeheerVoorkeurenController::inschakelen
  methods: POST
  requirements: { crid: '\d+', uid: '\d+' }
  options: { mag: P_CORVEE_MOD }

corvee-voorkeuren-beheer-uitschakelen:
  path: /corvee/voorkeuren/beheer/uitschakelen/{crid}/{uid}
  controller: CsrDelft\controller\maalcie\BeheerVoorkeurenController::uitschakelen
  methods: POST
  requirements: { crid: '\d+', uid: '\d+' }
  options: { mag: P_CORVEE_MOD }
