corvee-beheer:
  path: /corvee/beheer/{tid}/{mid}
  controller: CsrDelft\controller\maalcie\BeheerTakenController::beheer
  methods: GET
  defaults: { tid: null, mid: null, _mag: P_CORVEE_MOD }
  requirements: { tid: '\d+', mid: '\d+' }

corvee-beheer-prullenbak:
  path: /corvee/beheer/prullenbak
  controller: CsrDelft\controller\maalcie\BeheerTakenController::prullenbak
  methods: GET
  defaults: { _mag: P_CORVEE_MOD }

corvee-beheer-maaltijd:
  path: /corvee/beheer/maaltijd/{mid}
  controller: CsrDelft\controller\maalcie\BeheerTakenController::maaltijd
  methods: GET
  defaults: { mid: null, _mag: P_CORVEE_MOD }
  requirements: { mid: '\d+' }

corvee-beheer-herinneren:
  path: /corvee/beheer/herinneren
  controller: CsrDelft\controller\maalcie\BeheerTakenController::herinneren
  methods: GET
  defaults: { _mag: P_CORVEE_MOD }

corvee-beheer-nieuw:
  path: /corvee/beheer/nieuw/{mid}
  controller: CsrDelft\controller\maalcie\BeheerTakenController::nieuw
  methods: POST
  defaults: { mid: null, _mag: P_CORVEE_MOD }
  requirements: { mid: '\d+' }

corvee-beheer-bewerk:
  path: /corvee/beheer/bewerk/{tid}
  controller: CsrDelft\controller\maalcie\BeheerTakenController::bewerk
  methods: POST
  requirements: { tid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-beheer-opslaan:
  path: /corvee/beheer/opslaan/{tid}
  controller: CsrDelft\controller\maalcie\BeheerTakenController::opslaan
  methods: POST
  requirements: { tid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-beheer-verwijder:
  path: /corvee/beheer/verwijder/{tid}
  controller: CsrDelft\controller\maalcie\BeheerTakenController::verwijder
  methods: POST
  requirements: { tid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-beheer-herstel:
  path: /corvee/beheer/herstel/{tid}
  controller: CsrDelft\controller\maalcie\BeheerTakenController::herstel
  methods: POST
  requirements: { tid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-beheer-toewijzen:
  path: /corvee/beheer/toewijzen/{tid}
  controller: CsrDelft\controller\maalcie\BeheerTakenController::toewijzen
  methods: POST
  requirements: { tid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-beheer-puntentoekennen:
  path: /corvee/beheer/puntentoekennen/{tid}
  controller: CsrDelft\controller\maalcie\BeheerTakenController::puntentoekennen
  methods: POST
  requirements: { tid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-beheer-puntenintrekken:
  path: /corvee/beheer/puntenintrekken/{tid}
  controller: CsrDelft\controller\maalcie\BeheerTakenController::puntenintrekken
  methods: POST
  requirements: { tid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-beheer-email:
  path: /corvee/beheer/email/{tid}
  controller: CsrDelft\controller\maalcie\BeheerTakenController::email
  methods: POST
  requirements: { tid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-beheer-leegmaken:
  path: /corvee/beheer/leegmaken
  controller: CsrDelft\controller\maalcie\BeheerTakenController::leegmaken
  methods: POST
  defaults: { _mag: P_CORVEE_MOD }

corvee-beheer-aanmaken:
  path: /corvee/beheer/aanmaken/{crid}
  controller: CsrDelft\controller\maalcie\BeheerTakenController::aanmaken
  methods: POST
  requirements: { crid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

