corvee-vrijstellingen:
  path: /corvee/vrijstellingen
  controller: CsrDelft\controller\maalcie\BeheerVrijstellingenController::beheer
  methods: GET
  defaults: { _mag: P_CORVEE_MOD }

corvee-vrijstellingen-nieuw:
  path: /corvee/vrijstellingen/nieuw
  controller: CsrDelft\controller\maalcie\BeheerVrijstellingenController::nieuw
  methods: POST
  defaults: { _mag: P_CORVEE_MOD }

corvee-vrijstellingen-beheer-bewerk:
  path: /corvee/vrijstellingen/bewerk/{uid}
  controller: CsrDelft\controller\maalcie\BeheerVrijstellingenController::bewerk
  methods: POST
  requirements: { uid: '.{4}' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-vrijstellingen-beheer-opslaan:
  path: /corvee/vrijstellingen/opslaan/{uid}
  controller: CsrDelft\controller\maalcie\BeheerVrijstellingenController::opslaan
  methods: POST
  requirements: { uid: '.{4}' }
  defaults: { uid: null, _mag: P_CORVEE_MOD }

corvee-vrijstellingen-beheer-verwijder:
  path: /corvee/vrijstellingen/verwijder/{uid}
  controller: CsrDelft\controller\maalcie\BeheerVrijstellingenController::verwijder
  methods: POST
  requirements: { uid: '.{4}' }
  defaults: { _mag: P_CORVEE_MOD }
