corvee-repetities:
  path: /corvee/repetities/{crid}/{mrid}
  controller: CsrDelft\controller\maalcie\CorveeRepetitiesController::beheer
  methods: GET
  defaults: { crid: null, mrid: null, _mag: P_CORVEE_MOD }
  requirements: { crid: '\d+', mrid: '\d+' }

corvee-repetities-maaltijd:
  path: /corvee/repetities/maaltijd/{mrid}
  controller: CsrDelft\controller\maalcie\CorveeRepetitiesController::maaltijd
  methods: GET
  requirements: { crid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-repetities-nieuw:
  path: /corvee/repetities/nieuw/{mrid}
  controller: CsrDelft\controller\maalcie\CorveeRepetitiesController::nieuw
  methods: POST
  defaults: { mrid: null, _mag: P_CORVEE_MOD }
  requirements: { mrid: '\d+' }

corvee-repetities-bewerk:
  path: /corvee/repetities/bewerk/{crid}
  controller: CsrDelft\controller\maalcie\CorveeRepetitiesController::bewerk
  methods: POST
  requirements: { crid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-repetities-opslaan:
  path: /corvee/repetities/opslaan/{crid}
  controller: CsrDelft\controller\maalcie\CorveeRepetitiesController::opslaan
  methods: POST
  requirements: { crid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-repetities-verwijder:
  path: /corvee/repetities/verwijder/{crid}
  controller: CsrDelft\controller\maalcie\CorveeRepetitiesController::verwijder
  methods: POST
  requirements: { crid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-repetities-bijwerken:
  path: /corvee/repetities/bijwerken/{crid}
  controller: CsrDelft\controller\maalcie\CorveeRepetitiesController::bijwerken
  methods: POST
  requirements: { crid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

