corvee-functies:
  path: /corvee/functies/{fid}
  controller: CsrDelft\controller\maalcie\BeheerFunctiesController::beheer
  methods: GET
  requirements: { fid: '\d+' }
  defaults: { fid: null, _mag: P_CORVEE_MOD }

corvee-functies-toevoegen:
  path: /corvee/functies/toevoegen
  controller: CsrDelft\controller\maalcie\BeheerFunctiesController::toevoegen
  methods: POST
  defaults: { _mag: P_CORVEE_MOD }

corvee-functies-bewerken:
  path: /corvee/functies/bewerken/{fid}
  controller: CsrDelft\controller\maalcie\BeheerFunctiesController::bewerken
  methods: POST
  requirements: { fid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-functies-verwijderen:
  path: /corvee/functies/verwijderen/{fid}
  controller: CsrDelft\controller\maalcie\BeheerFunctiesController::verwijderen
  methods: POST
  requirements: { fid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-functies-kwalificeer:
  path: /corvee/functies/kwalificeer/{fid}
  controller: CsrDelft\controller\maalcie\BeheerFunctiesController::kwalificeer
  methods: POST
  requirements: { fid: '\d+' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-functies-dekwalificeer:
  path: /corvee/functies/dekwalificeer/{fid}/{uid}
  controller: CsrDelft\controller\maalcie\BeheerFunctiesController::dekwalificeer
  methods: POST
  requirements: { fid: '\d+', uid: '.{4}' }
  defaults: { _mag: P_CORVEE_MOD }
