corvee-mijn:
  path: /corvee
  controller: CsrDelft\controller\maalcie\MijnCorveeController::mijn
  methods: GET
  defaults: { _mag: P_CORVEE_IK }

corvee-rooster:
  path: /corvee/rooster/{toonverleden}
  controller: CsrDelft\controller\maalcie\MijnCorveeController::rooster
  methods: GET
  defaults: { toonverleden: null, _mag: P_CORVEE_IK }
