courant-toevoegen:
  path: /courant
  controller: CsrDelft\controller\CourantController::toevoegen
  methods: [GET,POST]
  defaults: { _mag: P_MAIL_POST }

courant-archief:
  path: /courant/archief
  controller: CsrDelft\controller\CourantController::archief
  methods: GET
  defaults: { _mag: P_LEDEN_READ }

courant-bekijken:
  path: /courant/bekijken/{id}
  controller: CsrDelft\controller\CourantController::bekijken
  methods: GET
  defaults: { _mag: P_LEDEN_READ }

courant-voorbeeld:
  path: /courant/voorbeeld
  controller: CsrDelft\controller\CourantController::voorbeeld
  methods: GET
  defaults: { _mag: P_LEDEN_READ }

courant-bewerken:
  path: /courant/bewerken/{id}
  controller: CsrDelft\controller\CourantController::bewerken
  methods: [GET,POST]
  defaults: { _mag: P_MAIL_POST }

courant-verwijderen:
  path: /courant/verwijderen/{id}
  controller: CsrDelft\controller\CourantController::verwijderen
  methods: POST
  defaults: { _mag: P_MAIL_POST }

courant-verzenden:
  path: /courant/verzenden/{iedereen}
  controller: CsrDelft\controller\CourantController::verzenden
  methods: POST
  defaults: { iedereen: null, _mag: P_MAIL_SEND }
