documenten:
  path: /documenten
  controller: CsrDelft\controller\DocumentenController::recenttonen
  methods: GET
  defaults: { _mag: P_DOCS_READ }

documenten-bekijken:
  path: /documenten/bekijken/{id}/{bestandsnaam}
  controller: CsrDelft\controller\DocumentenController::bekijken
  methods: GET
  requirements: { id: '\d+' }
  defaults: { _mag: P_DOCS_READ }

documenten-download:
  path: /documenten/download/{id}/{bestandsnaam}
  controller: CsrDelft\controller\DocumentenController::download
  methods: GET
  requirements: { id: '\d+' }
  defaults: { _mag: P_DOCS_READ }

documenten-categorie:
  path: /documenten/categorie/{id}
  controller: CsrDelft\controller\DocumentenController::categorie
  methods: GET
  requirements: { id: '\d+' }
  defaults: { _mag: P_DOCS_READ }

documenten-zoeken:
  path: /documenten/zoeken
  controller: CsrDelft\controller\DocumentenController::zoeken
  methods: [GET,POST]
  defaults: { _mag: P_DOCS_READ }

documenten-bewerken:
  path: /documenten/bewerken/{id}
  controller: CsrDelft\controller\DocumentenController::bewerken
  methods: [GET,POST]
  requirements: { id: '\d+' }
  defaults: { _mag: P_DOCS_MOD }

documenten-toevoegen:
  path: /documenten/toevoegen
  controller: CsrDelft\controller\DocumentenController::toevoegen
  methods: [GET,POST]
  defaults: { _mag: P_DOCS_MOD }

documenten-verwijderen:
  path: /documenten/verwijderen/{id}
  controller: CsrDelft\controller\DocumentenController::verwijderen
  methods: POST
  requirements: { id: '\d+' }
  defaults: { _mag: P_DOCS_MOD }
