eetplan:
  path: /eetplan
  controller: CsrDelft\controller\EetplanController::view
  methods: GET
  defaults: { _mag: P_LEDEN_READ }

eetplan-noviet:
  path: /eetplan/noviet/{uid}
  controller: CsrDelft\controller\EetplanController::noviet
  methods: GET
  requirements: { uid: '.{4}' }
  defaults: { _mag: P_LEDEN_READ }

eetplan-huis:
  path: /eetplan/huis/{id}
  controller: CsrDelft\controller\EetplanController::huis
  methods: GET
  requirements: { id: '\d+' }
  defaults: { _mag: P_LEDEN_READ }

eetplan-beheer:
  path: /eetplan/beheer
  controller: CsrDelft\controller\EetplanController::beheer
  methods: [GET,POST]
  defaults: { _mag: "P_ADMIN,commissie:NovCie" }

eetplan-bekendehuizen-toevoegen:
  path: /eetplan/bekendehuizen/toevoegen
  controller: CsrDelft\controller\EetplanController::bekendehuizen_toevoegen
  methods: POST
  defaults: { _mag: "P_ADMIN,commissie:NovCie" }

eetplan-bekendehuizen-verwijderen:
  path: /eetplan/bekendehuizen/verwijderen
  controller: CsrDelft\controller\EetplanController::bekendehuizen_verwijderen
  methods: POST
  defaults: { _mag: "P_ADMIN,commissie:NovCie" }

eetplan-bekendehuizen-zoeken:
  path: /eetplan/bekendehuizen/zoeken
  controller: CsrDelft\controller\EetplanController::bekendehuizen_zoeken
  methods: GET
  defaults: { _mag: "P_ADMIN,commissie:NovCie" }

eetplan-bekendehuizen-bewerken:
  path: /eetplan/bekendehuizen/bewerken/{uuid}
  controller: CsrDelft\controller\EetplanController::bekendehuizen_bewerken
  methods: POST
  defaults: { uuid: null, _mag: "P_ADMIN,commissie:NovCie" }

eetplan-bekendehuizen:
  path: /eetplan/bekendehuizen
  controller: CsrDelft\controller\EetplanController::bekendehuizen
  methods: POST
  defaults: { _mag: "P_ADMIN,commissie:NovCie" }

eetplan-novietrelatie:
  path: /eetplan/novietrelatie
  controller: CsrDelft\controller\EetplanController::novietrelatie
  methods: POST
  defaults: { _mag: "P_ADMIN,commissie:NovCie" }

eetplan-novietrelatie-toevoegen:
  path: /eetplan/novietrelatie/toevoegen
  controller: CsrDelft\controller\EetplanController::novietrelatie_toevoegen
  methods: POST
  defaults: { _mag: "P_ADMIN,commissie:NovCie" }

eetplan-novietrelatie-bewerken:
  path: /eetplan/novietrelatie/bewerken/{uuid}
  controller: CsrDelft\controller\EetplanController::novietrelatie_bewerken
  methods: POST
  defaults: { uuid: null, _mag: "P_ADMIN,commissie:NovCie" }

eetplan-novietrelatie-verwijderen:
  path: /eetplan/novietrelatie/verwijderen
  controller: CsrDelft\controller\EetplanController::novietrelatie_verwijderen
  methods: POST
  defaults: { _mag: "P_ADMIN,commissie:NovCie" }

eetplan-woonoord:
  path: /eetplan/woonoorden/{actie}
  controller: CsrDelft\controller\EetplanController::woonoorden
  methods: POST
  defaults: { actie: null, _mag: "P_ADMIN,commissie:NovCie" }

eetplan-nieuw:
  path: /eetplan/nieuw
  controller: CsrDelft\controller\EetplanController::nieuw
  methods: POST
  defaults: { _mag: "P_ADMIN,commissie:NovCie" }

eetplan-verwijderen:
  path: /eetplan/verwijderen
  controller: CsrDelft\controller\EetplanController::verwijderen
  methods: POST
  defaults: { _mag: "P_ADMIN,commissie:NovCie" }
