forum:
  path: /forum
  controller: CsrDelft\controller\ForumController::forum
  methods: GET
  options: { mag: P_PUBLIC }

forum-deel:
  path: /forum/deel/{forum_id}/{pagina}
  controller: CsrDelft\controller\ForumController::deel
  methods: [GET, POST]
  defaults: { pagina: 1 }
  requirements: { forum_id: '\d+', pagina: '\d+' }
  options: { mag: P_PUBLIC }

forum-zoeken:
  path: /forum/zoeken/{query}/{pagina}
  controller: CsrDelft\controller\ForumController::zoeken
  methods: [GET, POST]
  defaults: { query: null, pagina: 1}
  requirements: { pagina: '\d+' }
  options: { mag: P_PUBLIC }

forum-public-rss:
  path: /forum/rss/csrdelft.xml
  controller: CsrDelft\controller\ForumController::rss
  methods: GET
  options: { mag: P_PUBLIC }

forum-rss:
  path: /forum/rss/{token}/csrdelft.xml
  controller: CsrDelft\controller\ForumController::rss
  methods: GET
  options: { mag: P_PUBLIC }

forum-recent:
  path: /forum/recent/{pagina}
  controller: CsrDelft\controller\ForumController::recent
  methods: GET
  defaults: { pagina: 1 }
  requirements: { pagina: '\d+' }
  options: { mag: P_PUBLIC }

forum-recent-belangrijk:
  path: /forum/recent/{pagina}/belangrijk
  controller: CsrDelft\controller\ForumController::recent
  methods: GET
  requirements: { pagina: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-onderwerp:
  path: /forum/onderwerp/{draad_id}/{pagina}/{statistiek}
  controller: CsrDelft\controller\ForumController::onderwerp
  methods: GET
  defaults: { pagina: null, statistiek: null }
  requirements: { draad_id: '\d+' }
  options: { mag: P_PUBLIC }

forum-reactie:
  path: /forum/reactie/{post_id}
  controller: CsrDelft\controller\ForumController::reactie
  methods: GET
  options: { mag: P_PUBLIC }
  requirements: { post_id: '\d+' }

forum-titelzoeken:
  path: /forum/titelzoeken
  controller: CsrDelft\controller\ForumController::titelzoeken
  methods: GET
  options: { mag: P_LOGGED_IN }

forum-belangrijk:
  path: /forum/belangrijk/{pagina}
  controller: CsrDelft\controller\ForumController::belangrijk
  methods: GET
  defaults: { pagina: 1 }
  requirements: { pagina: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-wacht:
  path: /forum/wacht
  controller: CsrDelft\controller\ForumController::wacht
  methods: GET
  options: { mag: P_FORUM_MOD }

forum-posten:
  path: /forum/posten/{forum_id}/{draad_id}
  controller: CsrDelft\controller\ForumController::posten
  methods: POST
  defaults: { draad_id: null }
  requirements: { forum_id: '\d+', draad_id: '\d+' }
  options: { mag: P_PUBLIC }

forum-aanmaken:
  path: /forum/aanmaken
  controller: CsrDelft\controller\ForumController::aanmaken
  methods: POST
  options: { mag: P_FORUM_ADMIN }

forum-beheren:
  path: /forum/beheren/{forum_id}
  controller: CsrDelft\controller\ForumController::beheren
  methods: POST
  requirements: { forum_id: '\d+' }
  options: { mag: P_FORUM_ADMIN }

forum-opheffen:
  path: /forum/opheffen/{forum_id}
  controller: CsrDelft\controller\ForumController::opheffen
  methods: POST
  requirements: { forum_id: '\d+' }
  options: { mag: P_FORUM_ADMIN }

forum-bewerken:
  path: /forum/bewerken/{post_id}
  controller: CsrDelft\controller\ForumController::bewerken
  methods: POST
  requirements: { post_id: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-citeren:
  path: /forum/citeren/{post_id}
  controller: CsrDelft\controller\ForumController::citeren
  methods: POST
  requirements: { post_id: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-bladwijzer:
  path: /forum/bladwijzer/{draad_id}
  controller: CsrDelft\controller\ForumController::bladwijzer
  methods: POST
  requirements: { draad_id: '\d+' }
  options: { mag: P_LOGGED_IN}

forum-concept:
  path: /forum/concept/{forum_id}/{draad_id}
  controller: CsrDelft\controller\ForumController::concept
  methods: POST
  defaults: { draad_id: null }
  requirements: { forum_id: '\d+', draad_id: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-grafiekdata:
  path: /forum/grafiekdata/{type}
  controller: CsrDelft\controller\ForumController::grafiekdata
  methods: POST
  options: { mag: P_LOGGED_IN }

forum-wijzigen:
  path: /forum/wijzigen/{draad_id}/{property}
  controller: CsrDelft\controller\ForumController::wijzigen
  methods: POST
  requirements: { draad_id: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-verwijderen:
  path: /forum/verwijderen/{post_id}
  controller: CsrDelft\controller\ForumController::verwijderen
  methods: POST
  requirements: { post_id: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-verplaatsen:
  path: /forum/verplaatsen/{post_id}
  controller: CsrDelft\controller\ForumController::verplaatsen
  methods: POST
  requirements: { post_id: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-offtopic:
  path: /forum/offtopic/{post_id}
  controller: CsrDelft\controller\ForumController::offtopic
  methods: POST
  requirements: { post_id: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-goedkeuren:
  path: /forum/goedkeuren/{post_id}
  controller: CsrDelft\controller\ForumController::goedkeuren
  methods: POST
  requirements: { post_id: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-meldingsniveau:
  path: /forum/meldingsniveau/{draad_id}/{niveau}
  controller: CsrDelft\controller\ForumController::meldingsniveau
  methods: POST
  requirements: { draad_id: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-deelmelding:
  path: /forum/deelmelding/{forum_id}/{niveau}
  controller: CsrDelft\controller\ForumController::deelmelding
  methods: POST
  requirements: { forum_id: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-tekst:
  path: /forum/tekst/{post_id}
  controller: CsrDelft\controller\ForumController::tekst
  methods: POST
  requirements: { post_id: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-verbergen:
  path: /forum/verbergen/{draad_id}
  controller: CsrDelft\controller\ForumController::verbergen
  methods: POST
  requirements: { draad_id: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-tonen:
  path: /forum/tonen/{draad_id}
  controller: CsrDelft\controller\ForumController::tonen
  methods: POST
  requirements: { draad_id: '\d+' }
  options: { mag: P_LOGGED_IN }

forum-toonalles:
  path: /forum/toonalles
  controller: CsrDelft\controller\ForumController::toonalles
  methods: POST
  options: { mag: P_LOGGED_IN }
