leden-memory:
  path: /leden/memory
  controller: CsrDelft\controller\LedenMemoryController::memory
  methods: GET
  defaults: { _mag: P_OUDLEDEN_READ }

ledenmemory-score:
  path: /leden/memoryscore
  controller: CsrDelft\controller\LedenMemoryController::memoryscore
  methods: POST
  defaults: { groep: null, _mag: P_OUDLEDEN_READ }

ledenmemory-scores:
  path: /leden/memoryscores/{groep}
  controller: CsrDelft\controller\LedenMemoryController::memoryscores
  methods: POST
  defaults: { groep: null, _mag: P_OUDLEDEN_READ }

namen-leren:
  path: /leden/namen-leren
  controller: CsrDelft\controller\LedenMemoryController::namenleren
  methods: GET
  defaults: { _mag: P_LEDEN_READ }
