leden-lijst:
  path: /ledenlijst
  controller: CsrDelft\controller\LedenLijstController::lijst
  methods: [GET,POST]
  defaults: { _mag: P_OUDLEDEN_READ }

leden-verjaardagen:
  path: /leden/verjaardagen
  controller: CsrDelft\controller\ProfielController::verjaardagen
  methods: GET
  defaults: { _mag: P_OUDLEDEN_READ }
