maalcie-beheer-maaltijden-beheer:
  path: /maaltijden/beheer/{mid}
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::GET_beheer
  methods: GET
  defaults: { mid: null, _mag: P_MAAL_MOD }
  requirements: { mid: '\d+' }

maalcie-beheer-maaltijden-beheer-data:
  path: /maaltijden/beheer
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::POST_beheer
  methods: POST
  defaults: { _mag: P_MAAL_MOD }

maalcie-beheer-maaltijden-prullenbak:
  path: /maaltijden/beheer/prullenbak
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::GET_prullenbak
  methods: GET
  defaults: { _mag: P_MAAL_MOD }

maalcie-beheer-maaltijden-prullenbak-data:
  path: /maaltijden/beheer/prullenbak
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::POST_prullenbak
  methods: POST
  defaults: { _mag: P_MAAL_MOD }

maalcie-beheer-maaltijden-archief:
  path: /maaltijden/beheer/archief
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::GET_archief
  methods: GET
  defaults: { _mag: P_MAAL_MOD }

maalcie-beheer-maaltijden-archief-data:
  path: /maaltijden/beheer/archief
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::POST_archief
  methods: POST
  defaults: { _mag: P_MAAL_MOD }

maalcie-beheer-maaltijden-onverwerkt:
  path: /maaltijden/beheer/onverwerkt
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::onverwerkt
  methods: GET
  defaults: { _mag: P_MAAL_MOD }

maalcie-beheer-maaltijden-beoordelingen:
  path: /maaltijden/beheer/beoordelingen
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::GET_beoordelingen
  methods: GET
  defaults: { _mag: P_LOGGED_IN }

maalcie-beheer-maaltijden-beoordelingen-data:
  path: /maaltijden/beheer/beoordelingen
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::POST_beoordelingen
  methods: POST
  defaults: { _mag: P_LOGGED_IN }

maalcie-beheer-maaltijden-toggle:
  path: /maaltijden/beheer/toggle/{mid}
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::toggle
  methods: POST
  defaults: { _mag: P_MAAL_MOD }

maalcie-beheer-maaltijden-nieuw:
  path: /maaltijden/beheer/nieuw
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::nieuw
  methods: POST
  defaults: { _mag: P_MAAL_MOD }

maalcie-beheer-maaltijden-bewerk:
  path: /maaltijden/beheer/bewerk/{mid}
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::bewerk
  defaults: { mid: null, _mag: P_MAAL_MOD }
  requirements: { mid: '\d+' }
  methods: POST

maalcie-beheer-maaltijden-verwijder:
  path: /maaltijden/beheer/verwijder
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::verwijder
  methods: POST
  defaults: { _mag: P_MAAL_MOD }

maalcie-beheer-maaltijden-herstel:
  path: /maaltijden/beheer/herstel
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::herstel
  methods: POST
  defaults: { _mag: P_MAAL_MOD }

maalcie-beheer-maaltijden-aanmelden:
  path: /maaltijden/beheer/aanmelden
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::aanmelden
  methods: POST
  defaults: { _mag: P_MAAL_MOD }

maalcie-beheer-maaltijden-afmelden:
  path: /maaltijden/beheer/afmelden
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::afmelden
  methods: POST
  defaults: { _mag: P_MAAL_MOD }

maalcie-beheer-maaltijden-aanmaken:
  path: /maaltijden/beheer/aanmaken/{mrid}
  controller: CsrDelft\controller\maalcie\BeheerMaaltijdenController::aanmaken
  methods: POST
  requirements: { mrid: '\d+' }
  defaults: { _mag: P_MAAL_MOD }
