maalcie-maaltijden-repetities:
  path: /maaltijden/repetities/{mrid}
  controller: CsrDelft\controller\maalcie\MaaltijdRepetitiesController::beheer
  methods: GET
  defaults: { mrid: null }
  options: { mag: P_MAAL_MOD }

maalcie-maaltijden-repetities-nieuw:
  path: /maaltijden/repetities/nieuw
  controller: CsrDelft\controller\maalcie\MaaltijdRepetitiesController::nieuw
  methods: POST
  options: { mag: P_MAAL_MOD }

maalcie-maaltijden-repetities-bewerk:
  path: /maaltijden/repetities/bewerk/{mrid}
  controller: CsrDelft\controller\maalcie\MaaltijdRepetitiesController::bewerk
  methods: POST
  options: { mag: P_MAAL_MOD }

maalcie-maaltijden-repetities-opslaan:
  path: /maaltijden/repetities/opslaan/{mrid}
  controller: CsrDelft\controller\maalcie\MaaltijdRepetitiesController::opslaan
  methods: POST
  options: { mag: P_MAAL_MOD }

maalcie-maaltijden-repetities-verwijder:
  path: /maaltijden/repetities/verwijder/{mrid}
  controller: CsrDelft\controller\maalcie\MaaltijdRepetitiesController::verwijder
  methods: POST
  options: { mag: P_MAAL_MOD }

maalcie-maaltijden-repetities-bijwerken:
  path: /maaltijden/repetities/bijwerken/{mrid}
  controller: CsrDelft\controller\maalcie\MaaltijdRepetitiesController::bijwerken
  methods: POST
  options: { mag: P_MAAL_MOD }
