maalcie-maaltijden-boekjaar-beheer:
  path: /maaltijden/boekjaar
  controller: CsrDelft\controller\maalcie\MaalCieBoekjaarController::beheer
  methods: GET
  options: { mag: P_MAAL_SALDI }

maalcie-maaltijden-boekjaar-sluitboekjaar:
  path: /maaltijden/boekjaar/sluitboekjaar
  controller: CsrDelft\controller\maalcie\MaalCieBoekjaarController::sluitboekjaar
  methods: POST
  options: { mag: P_MAAL_SALDI }
