maalcie-maaltijden-abonnementen:
  path: /maaltijden/abonnementen
  controller: CsrDelft\controller\maalcie\MijnAbonnementenController::mijn
  methods: GET
  defaults: { _mag: P_MAAL_IK }

maalcie-maaltijden-abonnementen-inschakelen:
  path: /maaltijden/abonnementen/inschakelen/{mrid}
  controller: CsrDelft\controller\maalcie\MijnAbonnementenController::inschakelen
  requirements: { mrid: '\d+' }
  methods: POST
  defaults: { _mag: P_MAAL_IK }

maalcie-maaltijden-abonnementen-uitschakelen:
  path: /maaltijden/abonnementen/uitschakelen/{mrid}
  controller: CsrDelft\controller\maalcie\MijnAbonnementenController::uitschakelen
  requirements: { mrid: '\d+' }
  methods: POST
  defaults: { _mag: P_MAAL_IK }
