menubeheer-beheer:
  path: /menubeheer/beheer/{menu_name}
  controller: CsrDelft\controller\MenuBeheerController::beheer
  methods: GET
  defaults: { _mag: P_LOGGED_IN }

menubeheer-toevoegen:
  path: /menubeheer/toevoegen/{parent_id}
  controller: CsrDelft\controller\MenuBeheerController::toevoegen
  methods: POST
  defaults: { _mag: P_LOGGED_IN }

menubeheer-bewerken:
  path: /menubeheer/bewerken/{item_id}
  controller: CsrDelft\controller\MenuBeheerController::bewerken
  methods: POST
  requirements: { item_id: '\d+' }
  defaults: { _mag: P_LOGGED_IN }

menubeheer-verwijderen:
  path: /menubeheer/verwijderen/{item_id}
  controller: CsrDelft\controller\MenuBeheerController::verwijderen
  methods: POST
  requirements: { item_id: '\d+' }
  defaults: { _mag: P_LOGGED_IN }

menubeheer-zichtbaar:
  path: /menubeheer/zichtbaar/{item_id}
  controller: CsrDelft\controller\MenuBeheerController::zichtbaar
  methods: POST
  requirements: { item_id: '\d+' }
  defaults: { _mag: P_LOGGED_IN }
