peilingen-beheer:
  path: /peilingen/beheer/{id}
  controller: CsrDelft\controller\PeilingenController::table
  methods: GET
  requirements: { id: '\d+' }
  defaults: { id: null, _mag: P_PEILING_EDIT }

peilingen-beheer-post:
  path: /peilingen/beheer
  controller: CsrDelft\controller\PeilingenController::lijst
  methods: POST
  defaults: { _mag: P_PEILING_EDIT }

peilingen-opties-table:
  path: /peilingen/opties/{id}
  controller: CsrDelft\controller\PeilingOptiesController::table
  methods: GET
  requirements: { id: '\d+' }
  defaults: { _mag: P_PEILING_EDIT }

peilingen-opties-table-content:
  path: /peilingen/opties/{id}
  controller: CsrDelft\controller\PeilingOptiesController::lijst
  methods: POST
  requirements: { id: '\d+' }
  defaults: { _mag: P_PEILING_EDIT }

peilingen-opties-toevoegen:
  path: /peilingen/opties/{id}/toevoegen
  controller: CsrDelft\controller\PeilingOptiesController::toevoegen
  methods: POST
  requirements: { id: '\d+' }
  defaults: { _mag: P_PEILING_VOTE }

peilingen-opties-verwijderen:
  path: /peilingen/opties/verwijderen
  controller: CsrDelft\controller\PeilingOptiesController::verwijderen
  methods: POST
  defaults: { _mag: P_PEILING_EDIT }

peilingen-verwijderen:
  path: /peilingen/verwijderen
  controller: CsrDelft\controller\PeilingenController::verwijderen
  methods: [GET,POST]
  defaults: { _mag: P_PEILING_MOD }

peilingen-stem:
  path: /peilingen/stem/{id}
  controller: CsrDelft\controller\PeilingenController::stem
  methods: POST
  requirements: { id: '\d+' }
  defaults: { _mag: P_PEILING_VOTE }

peilingen-bewerken:
  path: /peilingen/bewerken
  controller: CsrDelft\controller\PeilingenController::bewerken
  methods: POST
  defaults: { _mag: P_PEILING_EDIT }

peilingen-nieuw:
  path: /peilingen/nieuw
  controller: CsrDelft\controller\PeilingenController::nieuw
  methods: POST
  defaults: { _mag: P_PEILING_EDIT }
