toestemming-overzicht:
  path: /toestemming
  controller: CsrDelft\controller\ToestemmingController::GET_overzicht
  methods: GET
  options: { mag: P_LOGGED_IN }

toestemming-opslaan:
  path: /toestemming
  controller: CsrDelft\controller\ToestemmingController::POST_overzicht
  methods: POST
  options: { mag: P_LOGGED_IN }

toestemming-annuleren:
  path: /toestemming/annuleren
  controller: CsrDelft\controller\ToestemmingController::GET_annuleren
  methods: GET
  options: { mag: P_LOGGED_IN }

toestemming-annuleren2:
  path: /toestemming/annuleren
  controller: CsrDelft\controller\ToestemmingController::POST_annuleren
  methods: POST
  options: { mag: P_LOGGED_IN }

toestemming-lijst:
  path: /toestemming/lijst
  controller: CsrDelft\controller\ToestemmingController::lijst
  methods: [GET,POST]
  options: { mag: P_LOGGED_IN }
