tools-bbcode:
  path: /tools/bbcode
  controller: CsrDelft\controller\ToolsController::bbcode
  methods: [GET,POST]
  defaults: { _mag: P_PUBLIC }

tools-dragobject:
  path: /tools/dragobject
  controller: CsrDelft\controller\ToolsController::dragobject
  methods: POST
  defaults: { _mag: P_LOGGED_IN }

tools-naamlink:
  path: /tools/naamlink
  controller: CsrDelft\controller\ToolsController::naamlink
  methods: [GET,POST]
  defaults: { _mag: P_OUDLEDEN_READ }

tools-roodschopper:
  path: /tools/roodschopper
  controller: CsrDelft\controller\ToolsController::roodschopper
  methods: [GET,POST]
  defaults: { _mag: P_FISCAAT_MOD }

tools-stats:
  path: /tools/stats
  controller: CsrDelft\controller\ToolsController::stats
  methods: GET
  defaults: { _mag: P_ADMIN }

tools-query:
  path: /tools/query
  controller: CsrDelft\controller\ToolsController::query
  methods: GET
  defaults: { _mag: P_LEDEN_READ }

tools-phpinfo:
  path: /tools/phpinfo
  controller: CsrDelft\controller\ToolsController::phpinfo
  methods: GET
  defaults: { _mag: P_ADMIN }

tools-admins:
  path: /tools/admins
  controller: CsrDelft\controller\ToolsController::admins
  methods: GET
  defaults: { _mag: P_LEDEN_READ }

tools-novieten:
  path: /tools/novieten
  controller: CsrDelft\controller\ToolsController::novieten
  methods: GET
  defaults: { _mag: "P_ADMIN,commissie:NovCie" }

tools-naamsuggesties:
  path: /tools/naamsuggesties
  controller: CsrDelft\controller\ToolsController::naamsuggesties
  methods: GET
  defaults: { _mag: P_OUDLEDEN_READ }

tools-streeplijst:
  path: /tools/streeplijst
  controller: CsrDelft\controller\ToolsController::streeplijst
  methods: GET
  defaults: { _mag: P_OUDLEDEN_READ }

tools-verticalelijsten:
  path: /tools/verticalelijsten
  controller: CsrDelft\controller\ToolsController::verticalelijsten
  methods: GET
  defaults: { _mag: P_ADMIN }

tools-memcachestats:
  path: /tools/memcachestats
  controller: CsrDelft\controller\ToolsController::memcachestats
  methods: GET
  defaults: { _mag: P_ADMIN }

tools-syncldap:
  path: /tools/syncldap
  controller: CsrDelft\controller\ToolsController::syncldap
  methods: GET
  defaults: { _mag: P_PUBLIC }

tools-patronaat:
  path: /tools/patronaat
  controller: CsrDelft\controller\ToolsController::patronaat
  methods: GET
  defaults: { _mag: P_LOGGED_IN }
