oauth2_authorize:
  path: /authorize
  controller: Trikoder\Bundle\OAuth2Bundle\Controller\AuthorizationController::indexAction
  methods: GET

oauth2_token:
  path: /api/v3/token
  controller: Trikoder\Bundle\OAuth2Bundle\Controller\TokenController::indexAction
  methods: POST
  defaults: { _csrfUnsafe: ja }

