wachtwoord-wijzigen:
  path: /wachtwoord/wijzigen
  controller: CsrDelft\controller\WachtwoordController::wijzigen
  methods: [GET,POST]
  options: { mag: P_LOGGED_IN }

wachtwoord-reset:
  path: /wachtwoord/reset
  controller: CsrDelft\controller\WachtwoordController::reset
  methods: [GET,POST]
  options: { mag: P_PUBLIC }

wachtwoord-vergeten:
  path: /wachtwoord/vergeten
  controller: CsrDelft\controller\WachtwoordController::vergeten
  methods: [GET,POST]
  options: { mag: P_PUBLIC }

wachtwoord-verlopen:
  path: /wachtwoord/verlopen
  controller: CsrDelft\controller\WachtwoordController::wijzigen
  methods: GET
  options: { mag: P_LOGGED_IN }
