# Services die alleen nodig zijn bij dev.

services:
  CsrDelft\common\SuDataCollector:
    tags:
      - name:     data_collector
        template: 'data_collector/su.html.twig'
        # must match the value returned by the getName() method
        id: 'csr.su'
    public: false
