monolog:
    handlers:
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: critical
        slackwebhook:
            type: slackwebhook
            webhook_url: '%env(SLACK_URL)%'
            channel: '%env(SLACK_CHANNEL)%'
            icon_emoji: '%env(SLACK_ICON)%'
            bot_name: '%env(SLACK_USERNAME)%'
            include_extra: true
            level: critical
